-- ============================================
-- Food Discovery and Review Platform
-- MySQL Database Schema
-- ============================================

CREATE DATABASE IF NOT EXISTS food_finds CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE food_finds;

-- Categories table
CREATE TABLE IF NOT EXISTS categories (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    icon VARCHAR(10) DEFAULT '🍽️'
);

-- Users table (custom auth - stores user accounts)
CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Restaurants table
CREATE TABLE IF NOT EXISTS restaurants (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    description TEXT,
    category_id INT,
    address VARCHAR(300) DEFAULT '',
    phone VARCHAR(50) DEFAULT '',
    image_url VARCHAR(500) DEFAULT '',
    latitude DECIMAL(10, 7) DEFAULT 0,
    longitude DECIMAL(10, 7) DEFAULT 0,
    price_range VARCHAR(10) DEFAULT '$$',
    hours VARCHAR(200) DEFAULT '',
    user_id INT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE SET NULL,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- Menu items table
CREATE TABLE IF NOT EXISTS menu_items (
    id INT AUTO_INCREMENT PRIMARY KEY,
    restaurant_id INT NOT NULL,
    name VARCHAR(200) NOT NULL,
    description TEXT,
    price DECIMAL(10, 2) NOT NULL DEFAULT 0,
    category VARCHAR(100) DEFAULT 'Mains',
    image_url VARCHAR(500) DEFAULT '',
    is_vegetarian BOOLEAN DEFAULT FALSE,
    FOREIGN KEY (restaurant_id) REFERENCES restaurants(id) ON DELETE CASCADE
);

-- Reviews table
CREATE TABLE IF NOT EXISTS reviews (
    id INT AUTO_INCREMENT PRIMARY KEY,
    restaurant_id INT NOT NULL,
    user_id INT NOT NULL,
    rating INT NOT NULL CHECK (rating >= 1 AND rating <= 5),
    comment TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (restaurant_id) REFERENCES restaurants(id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- Favorites table
CREATE TABLE IF NOT EXISTS favorites (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    restaurant_id INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY unique_favorite (user_id, restaurant_id),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (restaurant_id) REFERENCES restaurants(id) ON DELETE CASCADE
);

-- ============================================
-- Seed Data
-- ============================================

-- Categories
INSERT INTO categories (name, icon) VALUES
('Italian', '🍝'),
('Chinese', '🥡'),
('Indian', '🍛'),
('Mexican', '🌮'),
('American', '🍔'),
('Japanese', '🍣'),
('Thai', '🍜'),
('Desserts', '🍰');

-- Demo user (password: password123)
-- The password hash is generated by PHP's password_hash() with BCRYPT
INSERT INTO users (name, email, password) VALUES
('Demo User', 'demo@foodapp.com', '$2y$10$N9qo8uLOickgx2ZMRZoMy.MrqJZDoDqIEmKmJXKgFqk6JqQYJSBqe');

-- Restaurants
INSERT INTO restaurants (name, description, category_id, address, phone, latitude, longitude, price_range, hours, user_id) VALUES
('Bella Italia', 'Authentic Italian cuisine with handmade pasta and wood-fired pizzas. Family-owned since 1985.', 5, '123 Main Street, Springfield', '(555) 123-4567', 40.7128, -74.0060, '$$', 'Mon-Sun: 11:00 AM - 10:00 PM', 1),
('Dragon Wok', 'Traditional Chinese dishes with a modern twist. Famous for dim sum and Peking duck.', 2, '456 Oak Avenue, Riverside', '(555) 234-5678', 40.7200, -74.0100, '$$', 'Mon-Sat: 10:00 AM - 9:30 PM', 1),
('Spice Garden', 'Authentic Indian flavors from north and south. Vegetarian options available for every dish.', 3, '789 Curry Lane, Midtown', '(555) 345-6789', 40.7050, -73.9900, '$', 'Mon-Sun: 11:00 AM - 11:00 PM', 1),
('El Mariachi', 'Vibrant Mexican restaurant with tacos, burritos, and fresh guacamole made at your table.', 7, '321 Fiesta Blvd, Downtown', '(555) 456-7890', 40.7180, -74.0150, '$$', 'Mon-Sun: 10:00 AM - 12:00 AM', 1),
('Burger Joint', 'Classic American burgers, fries, and milkshakes. All beef is locally sourced.', 1, '654 Burger Road, Uptown', '(555) 567-8901', 40.7250, -74.0000, '$', 'Mon-Sun: 10:00 AM - 11:00 PM', 1),
('Sushi Express', 'Fresh sushi and sashimi prepared daily by our master chefs. Omakase available.', 6, '987 Sakura Street, Eastside', '(555) 678-9012', 40.7100, -73.9850, '$$$', 'Tue-Sun: 11:30 AM - 10:00 PM', 1),
('Bangkok Street', 'Authentic Thai street food with bold flavors. Try our famous pad thai and green curry.', 8, '147 Thai Plaza, Westside', '(555) 789-0123', 40.7150, -74.0200, '$$', 'Mon-Sat: 11:00 AM - 10:00 PM', 1),
('Sweet Tooth', 'Dessert cafe with cakes, pastries, ice cream, and specialty coffee. Perfect for afternoon treats.', 4, '258 Sugar Street, Old Town', '(555) 890-1234', 40.7190, -73.9950, '$', 'Mon-Sun: 9:00 AM - 10:00 PM', 1);

-- Menu items for Bella Italia (restaurant 1)
INSERT INTO menu_items (restaurant_id, name, description, price, category, is_vegetarian) VALUES
(1, 'Margherita Pizza', 'Fresh mozzarella, basil, and tomato sauce on hand-tossed dough', 14.99, 'Mains', TRUE),
(1, 'Spaghetti Carbonara', 'Pasta with pancetta, egg, parmesan, and black pepper', 16.99, 'Mains', FALSE),
(1, 'Bruschetta', 'Grilled bread with tomatoes, garlic, and olive oil', 8.99, 'Appetizers', TRUE),
(1, 'Tiramisu', 'Coffee-soaked ladyfingers with mascarpone cream', 7.99, 'Desserts', TRUE),
(1, 'Lasagna', 'Layered pasta with beef ragu and bechamel sauce', 17.99, 'Mains', FALSE),
(1, 'Caprese Salad', 'Fresh mozzarella, tomatoes, and basil with olive oil', 10.99, 'Appetizers', TRUE);

-- Menu items for Dragon Wok (restaurant 2)
INSERT INTO menu_items (restaurant_id, name, description, price, category, is_vegetarian) VALUES
(2, 'Kung Pao Chicken', 'Diced chicken with peanuts, vegetables, and chili peppers', 13.99, 'Mains', FALSE),
(2, 'Vegetable Lo Mein', 'Stir-fried noodles with mixed vegetables', 10.99, 'Mains', TRUE),
(2, 'Pork Dumplings', 'Steamed dumplings filled with seasoned pork', 9.99, 'Appetizers', FALSE),
(2, 'Hot and Sour Soup', 'Spicy and tangy soup with tofu and mushrooms', 5.99, 'Appetizers', TRUE),
(2, 'Peking Duck', 'Crispy duck with hoisin sauce and pancakes', 28.99, 'Mains', FALSE);

-- Menu items for Spice Garden (restaurant 3)
INSERT INTO menu_items (restaurant_id, name, description, price, category, is_vegetarian) VALUES
(3, 'Butter Chicken', 'Creamy tomato-based curry with tender chicken', 15.99, 'Mains', FALSE),
(3, 'Vegetable Biryani', 'Fragrant rice with mixed vegetables and spices', 12.99, 'Mains', TRUE),
(3, 'Samosas', 'Crispy pastries filled with spiced potatoes and peas', 6.99, 'Appetizers', TRUE),
(3, 'Paneer Tikka', 'Grilled cottage cheese with yogurt and spices', 13.99, 'Mains', TRUE),
(3, 'Gulab Jamun', 'Deep-fried milk dumplings in sugar syrup', 5.99, 'Desserts', TRUE);

-- Menu items for El Mariachi (restaurant 4)
INSERT INTO menu_items (restaurant_id, name, description, price, category, is_vegetarian) VALUES
(4, 'Beef Tacos', 'Three soft tacos with seasoned beef, salsa, and cilantro', 11.99, 'Mains', FALSE),
(4, 'Chicken Burrito', 'Grilled chicken with rice, beans, and guacamole', 12.99, 'Mains', FALSE),
(4, 'Guacamole', 'Fresh avocado dip with lime and cilantro', 7.99, 'Appetizers', TRUE),
(4, 'Nachos Supreme', 'Tortilla chips with cheese, jalapenos, and salsa', 9.99, 'Appetizers', TRUE),
(4, 'Churros', 'Fried dough with cinnamon sugar and chocolate dip', 6.99, 'Desserts', TRUE);

-- Menu items for Burger Joint (restaurant 5)
INSERT INTO menu_items (restaurant_id, name, description, price, category, is_vegetarian) VALUES
(5, 'Classic Cheeseburger', 'Beef patty with cheddar, lettuce, tomato, and pickles', 9.99, 'Mains', FALSE),
(5, 'Veggie Burger', 'Plant-based patty with avocado and sprouts', 10.99, 'Mains', TRUE),
(5, 'Loaded Fries', 'Fries with cheese, bacon, and green onions', 7.99, 'Sides', FALSE),
(5, 'Chocolate Milkshake', 'Thick chocolate shake with whipped cream', 5.99, 'Drinks', TRUE),
(5, 'Onion Rings', 'Crispy battered onion rings', 6.99, 'Sides', TRUE);

-- Menu items for Sushi Express (restaurant 6)
INSERT INTO menu_items (restaurant_id, name, description, price, category, is_vegetarian) VALUES
(6, 'California Roll', 'Crab, avocado, and cucumber rolled in rice', 8.99, 'Mains', FALSE),
(6, 'Salmon Sashimi', 'Six pieces of fresh raw salmon', 14.99, 'Mains', FALSE),
(6, 'Edamame', 'Steamed soybeans with sea salt', 5.99, 'Appetizers', TRUE),
(6, 'Tempura Shrimp', 'Lightly battered and fried shrimp', 11.99, 'Appetizers', FALSE),
(6, 'Mochi Ice Cream', 'Sweet rice cake with ice cream filling', 6.99, 'Desserts', TRUE);

-- Menu items for Bangkok Street (restaurant 7)
INSERT INTO menu_items (restaurant_id, name, description, price, category, is_vegetarian) VALUES
(7, 'Pad Thai', 'Stir-fried rice noodles with shrimp, egg, and peanuts', 12.99, 'Mains', FALSE),
(7, 'Green Curry', 'Thai green curry with chicken and bamboo shoots', 13.99, 'Mains', FALSE),
(7, 'Tom Yum Soup', 'Spicy and sour soup with shrimp and lemongrass', 7.99, 'Appetizers', FALSE),
(7, 'Vegetable Spring Rolls', 'Crispy rolls with cabbage and carrots', 5.99, 'Appetizers', TRUE),
(7, 'Mango Sticky Rice', 'Sweet sticky rice with fresh mango', 6.99, 'Desserts', TRUE);

-- Menu items for Sweet Tooth (restaurant 8)
INSERT INTO menu_items (restaurant_id, name, description, price, category, is_vegetarian) VALUES
(8, 'Chocolate Lava Cake', 'Warm cake with a molten chocolate center', 8.99, 'Desserts', TRUE),
(8, 'Vanilla Ice Cream', 'Two scoops of homemade vanilla ice cream', 4.99, 'Desserts', TRUE),
(8, 'New York Cheesecake', 'Creamy cheesecake with graham crust', 7.99, 'Desserts', TRUE),
(8, 'Cappuccino', 'Espresso with steamed milk and foam', 4.49, 'Drinks', TRUE),
(8, 'Tiramisu Cup', 'Individual tiramisu with cocoa dusting', 6.99, 'Desserts', TRUE);

-- Reviews
INSERT INTO reviews (restaurant_id, user_id, rating, comment) VALUES
(1, 1, 5, 'Best Italian food in town! The pasta is made fresh daily and you can taste the difference.'),
(1, 1, 4, 'Great pizza and friendly service. Will definitely come back!'),
(2, 1, 4, 'Authentic flavors and generous portions. The dim sum is a must-try.'),
(3, 1, 5, 'Amazing biryani! The spices are perfectly balanced. Highly recommend.'),
(4, 1, 4, 'Fun atmosphere and delicious tacos. The guacamole is made fresh at your table!'),
(5, 1, 3, 'Good burgers but the wait time was a bit long. Food was fresh though.'),
(6, 1, 5, 'The freshest sushi I have ever had. The salmon sashimi melts in your mouth.'),
(7, 1, 4, 'Great Thai food with bold flavors. The pad thai is excellent!'),
(8, 1, 5, 'The chocolate lava cake is to die for! Perfect place for dessert lovers.');
